.PHONY: clean All

All:
	@echo "----------Building project:[ Vending_Machine - Debug ]----------"
	@cd "Vending_Machine" && "$(MAKE)" -f  "Vending_Machine.mk"
clean:
	@echo "----------Cleaning project:[ Vending_Machine - Debug ]----------"
	@cd "Vending_Machine" && "$(MAKE)" -f  "Vending_Machine.mk" clean
